"""Update models

Revision ID: 26a55ee72ff9
Revises: eac851792c76
Create Date: 2026-07-16 11:51:47.015039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26a55ee72ff9'
down_revision = 'eac851792c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_salary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_salary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('job_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_jobs_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_location'), ['location'], unique=False)
        batch_op.drop_column('salary')

    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_constraint(batch_op.f('recruiters_company_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_recruiters_company_email'), ['company_email'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruiters_company_email'))
        batch_op.create_unique_constraint(batch_op.f('recruiters_company_email_key'), ['company_email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_jobs_location'))
        batch_op.drop_index(batch_op.f('ix_jobs_company'))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('job_type')
        batch_op.drop_column('max_salary')
        batch_op.drop_column('min_salary')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
