"""add interview model and interview scheduled status

Revision ID: 276ea069842a
Revises: 3b9971358ed0
Create Date: 2026-07-23 15:33:44.543346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276ea069842a'
down_revision = '3b9971358ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
