"""Added Interview table

Revision ID: 2ffab720c01e
Revises: 26a55ee72ff9
Create Date: 2026-07-18 16:32:42.986576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffab720c01e'
down_revision = '26a55ee72ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interview_date', sa.String(length=30), nullable=False),
    sa.Column('interview_time', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['candidate_id'])
        batch_op.create_foreign_key(None, 'users', ['candidate_id'], ['id'])

    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_saved_job', ['candidate_id', 'job_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('unique_saved_job', type_='unique')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('interviews')
    # ### end Alembic commands ###
