"""Update Job model

Revision ID: ecc75fb96e14
Revises: a51ba2b32a84
Create Date: 2026-07-10 18:16:52.595472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecc75fb96e14'
down_revision = 'a51ba2b32a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('skills',
               existing_type=sa.String(length=150),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
